### ISSUE TITLE
Incorrect header check

### ISSUE THREAD

**Issue by DeiranZ** [Atem1995/game_library#1]
Hey! Awesome repo, although I can't get the .gz compression it to work in my case. I followed your steps in [here](https://gist.github.com/natrim/1a19f4b7668e0474897f3f28171f3b33?permalink_comment_id=4108811#gistcomment-4108811), but I keep getting an `Uncaught (in promise) incorrect header check` error. I'm using the same pako_inflate.min.js as you, Godot 3.4.4 and I triple checked the .html file and .js file. Could it be that there is something wrong with the compressed files? I tried using both gzip on linux and 7zip on windows to compress, but both throw the same error. I tried using inflateRaw in the .js file too, but it also crashes on loading.

**Comment by Visense6** [comment]
[game_library](https://github.com/Atem1995/game_library)/dodge_the_creeps/
I'm not sure where you are going wrong, you can refer to the example I linked above.
![1](https://user-images.githubusercontent.com/52338846/162195891-28f5b154-b9ba-4ae8-a3d0-d7013b53d2e4.PNG)
![2](https://user-images.githubusercontent.com/52338846/162195910-24f231f7-8eb5-4234-b64a-aa347c2d0a0f.PNG)
![3](https://user-images.githubusercontent.com/52338846/162195919-b427b69f-fbb8-4347-a49c-353a8eda31da.PNG)

**Comment by DeiranZ** [comment]
Turns out that my .htaccess file was messing it up, it works lovely after deleting it! Thank you!

**Comment by Visense6** [comment]
> Turns out that my .htaccess file was messing it up, it works lovely after deleting it! Thank you!

You are welcome at any time. You can also modify the corresponding code of the HTML5 export template, so that you don't need to modify the corresponding code every time after exporting.
